version: 2.1
orbs:
  codecov: codecov/codecov@1.1.0
executors:
  python3:
    docker:
      - image: circleci/python:3.7
jobs:
  test_python3:
    executor: python3
    steps:
      - checkout 
      - run: pip install -r requirements.txt
      - run: coverage run -m unittest discover
      - run: coverage xml
      - codecov/upload:
          file: coverage.xml
          token: $CODECOV_TOKEN
          upload_name: "Spylib-${CIRCLE_SHA1}"
workflows:
  test:
    jobs:
      - test_python3
