version: 2.1
executors:
  python3:
    docker:
      - image: circleci/python:3.7
jobs:
  test_python3:
    executor: python3
    steps:
      - checkout 
      - run: pip install -r requirements.txt
      - run: python3 -m unittest

workflows:
  test:
    jobs:
      - test_python3
